name: Release

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  release:
    name: Release copyfu
    runs-on: ubuntu-latest
    permissions:
      contents: write # Create GitHub release
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          no-cache: true

      - name: Check version in package.json
        run: |
          version=$(bun -p 'import { version } from "./package.json"; version')
          test "$version" = "${GITHUB_REF_NAME}"

      - name: Install dependencies
        run: |
          bun install

      - name: Generate a changelog
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md

      - name: Zip extensions
        run: |
          bun run zip
          bun run zip:firefox

      - name: Create Release
        run: |
          gh release create "${GITHUB_REF_NAME}" \
              --title "v${GITHUB_REF_NAME}" \
              --notes "${RELEASE_NOTES}" \
              .output/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: ${{ steps.git-cliff.outputs.content }}
