name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Check version in package.json
        run: |
          version=$(bun -p 'import { version } from "./package.json"; version')
          test "$version" = "${{ github.ref_name }}"

      - name: Install dependencies
        run: |
          bun install

      - name: Generate a changelog
        uses: orhun/git-cliff-action@e16f179f0be49ecdfe63753837f20b9531642772 # v4.7.0
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md

      - name: Zip extensions
        run: |
          bun run zip
          bun run zip:firefox

      - name: Create Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          artifacts: ".output/*.zip"
          artifactContentType: application/octet-stream
          name: v${{ github.ref_name }}
          body: ${{ steps.git-cliff.outputs.content }}
          token: ${{ secrets.GITHUB_TOKEN }}
